server:
  port: 8085

spring:
  application:
    name: video-service

#请求文件的最大值
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/feiyu-plus?characterEncoding=utf8&useSSL=false&useTimeZone=true&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: myroot

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取服务时间
  instance:
    lease-expiration-duration-in-seconds: 15 #过期时间
    lease-renewal-interval-in-seconds: 5   #心跳时间

mybatis:
  type-aliases-package: com.entity  #因为已经依赖interface，所以可以直接扫描
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.entity
  global-config:
    db-column-underline: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#七牛云sdk
qiniu:
  accessKey: 5C_fZFpH2vB2DZ6IRc0dhtOWMZ-83Y_sKKiH63vU
  secretKey: PDoHLfN8vQFm2KraiW9Y6E3puD9yYRMaFFZu8CyJ
  bucket: xiake-project
  path: q8es6w99e.bkt.clouddn.com

