server:
  port: 8084

spring:
  application:
    name: user-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/feiyu-plus?characterEncoding=utf8&useSSL=false&useTimeZone=true&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: myroot

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15 #过期时间
    lease-renewal-interval-in-seconds: 5   #心跳时间

mybatis:
  type-aliases-package: com.entity  #因为已经依赖interface，所以可以直接扫描
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.entity
  global-config:
    db-column-underline: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#安全配置
security:
  oauth2:
    resource:
      id: user-service
      #指定用户信息地址
      user-info-uri: https://localhost:10086/auth/user
      prefer-token-info: false