#网关，由nginx监听80，转发到10081
#启动：start nginx.exe
#重新加载：nginx.exe -s reload
server:
  port: 10081

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    user-service: /user/**


