#网关，由nginx监听80，转发到10081
#启动：start nginx.exe
#重新加载：nginx.exe -s reload
server:
  port: 10081

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    user-service: /user/**
    video-service: /video/**

    auth: #认证服务
      #响应的路径
      path: /auth/**
      #敏感头信息
      sensitiveHeaders:
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
      serviceId:  auth-service
  #添加代理头
  add-proxy-headers: true


